### ISSUE TITLE
Suggestion: make small highlights where revenants(big skulls) are located

### ISSUE THREAD

**Issue by xerance** [arturino009/ExpeditionIcons#1]
Would be neat if we could have an option to mark revenants(big skulls) and perhaps customize color/size, Would make planning logbooks even easier!

Great job btw, plugin is godsent.

edit: a check box for "Runic Monsters have 35% chance to drop an additional Stacked Deck" would also be very neat. super powerful for logbooks

**Comment by arturino009** [comment]
I think I added most of the things and also some more. Mby will add toggles to remnants if I'm not lazy

**Comment by xerance** [comment]
Nicely done! good job! 

2 small things:
-For map expedition: It would be nice to add a warning toggle for monsters drop corrupted items as this will corrupt logbooks as well.
-An option to toggle on/off the route optimizer as it seems to be a bit buggy in logbooks trying to path over unwalkable areas. not to mention it seems to flicker a lot in and out.

**Comment by xerance** [comment]
Works very well now, thanks a ton!

I'm unsure if this is a bug or intended, but it seems like the logbook pathing for artifacts/chest goes out of its way and tries to path and pickup heist chests, are these counted as basic currency? couldn't see a checkbox for them. 

Talking about this icon: https://puu.sh/J85f1/b2b72163d8.png

**Comment by arturino009** [comment]
No, the heist chests are just selected by default, since its mostly profit (as per some content creators). It is possible to add a toggle, but it is already getting pretty cluttered

**Comment by arturino009** [comment]
Added a toggle
