### ISSUE TITLE
Map/logbook planner

### ISSUE THREAD

**Issue by elvese** [arturino009/ExpeditionIcons#9]
I have just noticed its not working anymore as it used in past leagues, is it known issue or its just on my site ?
I mean its this feature when you press f6 or f7 and script shows most efficient explosive placement it seems bugged and shows only 3 placements
![Screenshot_52](https://user-images.githubusercontent.com/18148889/188081040-0dd57017-5352-45c8-914a-c76f496748b4.png)

**Comment by elvese** [comment]
![Screenshot_52](https://user-images.githubusercontent.com/18148889/188081111-da324613-c98a-4d6b-a502-3a90b3026fe7.png)

**Comment by arturino009** [comment]
Maybe fixed now?

**Comment by elvese** [comment]
looks like working well, thanks alot buddy
